// for tilemap creation, create tiles with a sprite info and
// a collider setting for Graph parsing
export class Grass {
  sprite = [5, 0];
  collider: boolean = false;
}

export class Tree {
  sprite = [13, 9];
  collider: boolean = true;
}

// load tiles array with tiles, doing this separately so that i can
// a-> use it for Excalibur's tilemap
// and b-> pass it to Graph for pathfinding
export const tiles = [
  new Grass(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Tree(),
  new Tree(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Tree(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Tree(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Tree(),
  new Grass(),
  new Grass(),
  new Grass(),
  new Grass(),
];
